version: '3.8'
services:
  mongodb:
    image: mongo:6
    container_name: mongodb-data
    ports:
      - '27017:27017' 
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '6000:6000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/employees_db 

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '5000:5000'
    depends_on:
      - backend

volumes:
  mongodb_data:

